var celigotest1 = function(){
r = nlapiCreateRecord("salesorder", {"customform":128});
r.setFieldValue("entity", 7657792);
r.setFieldText("custbody_celigo_etail_channel", "Shopify");
r.setFieldValue("custbody_celigo_etail_order_id", "4731356578008");
r.setFieldValue("custbody_celigo_shopify_order_no", "1013");
r.setFieldValue("custbody_celigo_shopify_discountcode", null);
r.setFieldText("orderstatus", "Pending Fulfillment");
r.setFieldValue("otherrefnum", "DHUB1013");
r.setFieldValue("billaddr1", "123 Fake st.");
r.setFieldValue("billaddr2", null);
r.setFieldValue("billaddressee", "Steve Dennis");
r.setFieldValue("billattention", "Springfree Trampoline");
r.setFieldValue("billcity", "Allen");
r.setFieldValue("billstate", "TX");
r.setFieldValue("billzip", "75013");
r.setFieldValue("billphone", "15555555555");
r.setFieldValue("billcountry", "US");
r.setFieldValue("shipaddr1", "123 Fake st.");
r.setFieldValue("shipaddr2", null);
r.setFieldValue("shipaddressee", "Steve Dennis");
r.setFieldValue("shipattention", "Springfree Trampoline");
r.setFieldValue("shipcity", "Allen");
r.setFieldValue("shipstate", "TX");
r.setFieldValue("shipzip", "75013");
r.setFieldValue("shipphone", "15555555555");
r.setFieldValue("shipcountry", "US");
r.setFieldValue("shipmethod", 3);
r.setFieldValue("custbody_celigo_shopify_giftcard_id", null);
r.setFieldText("custbody_celigo_etail_risk_rating", "Low");
r.setFieldValue("custbody_celigo_etail_risk_analysis", "Shopify recommendation");
r.setFieldValue("custbody_celigo_shpfy_transaction_ids", "5535558467800");
r.setFieldValue("custbody_celigo_shpfy_updatedtime", "2022-04-10T21:02:00-04:00");
r.setFieldValue("custbody_celigo_etail_transaction_ids", "pi_3KnBdgQs7HvXNsfi0EeTMWXr");
r.setFieldValue("custbody_celigo_shpfy_ispickup", "F");
r.setFieldValue("currency", 2);
r.setFieldValue("department", 60);
r.setFieldValue("custbody_notesspecialrequests", null);
r.setFieldValue("custbodycustbody_referralsource", 20);
r.setFieldValue("custbody_salessource", 2);
r.setFieldValue("trandate", "4/11/2022");
r.setFieldValue("custbody_celigo_shopify_store", 701);
r.setFieldValue("shippingcost", 0);
r.setFieldValue("externalid", "SHPF-61638738136-4731356578008");
r.setFieldValue("custbody_celigo_pre_order_submit_data", "{\"items\":{\"12116434682072\":{\"taxAmount\":\"0\",\"taxrate1\":0}},\"istaxable\":false,\"taxrate\":0,\"taxitem\":null}");
r.setFieldValue("custbody_celigo_etail_bill_exp", "F");
r.selectNewLineItem("item");
r.setCurrentLineItemValue("item", "item", 906);
r.setCurrentLineItemValue("item", "quantity", 1);
r.setCurrentLineItemValue("item", "pricelevel", -1);
r.setCurrentLineItemValue("item", "custcol_celigo_etail_order_line_id", "12116434682072");
r.setCurrentLineItemValue("item", "custcol_celigo_etail_fulfillment_serv", "manual");
r.setCurrentLineItemValue("item", "rate", "1375.00");
r.setCurrentLineItemValue("item", "custcol_celigo_etail_order_line_tax", "0");
r.commitLineItem("item");
nlapiSubmitRecord(r, false, false);
};